### PR TITLE
Update Fabric version to 1.16.3

### PR DESCRIPTION
**Pull request by NeRdTheNed**
This pull request changes a fair amount of things, so I'll split the changes into categories.

Behavioural changes / bugfixes:
- Fixes villager pathfinding for bamboo doors by registering their material wooden. This change is unfortunately unavoidable if this issue is to be fixed, as villagers are hardcoded to only pathfind through doors which are made out of the wood material type.
- Merges BetaCarotina's recipe advancements into the Fabric version.
- Changes the fences to be classified as wooden fences, instead of "other" fences (currently only used by nether brick fences). This means that they will now join up with wooden fences, instead of "other" fences.
- Adds more tags to various blocks. (Side note: all tags break in development, but work in production. No idea why, and apparently this is supposed to happen.)
- Adds a burn time to all bamboo items, based on vanilla burn times.
- Adds a .json extension to the pirate language file.
- Replaces the default mod icon with the bamboo bundle texture.

Development changes: 
- Switches from using Registry.ITEM.add / Registry.BLOCK.add to Registry.register.
- Adds a Github actions workflow, which automatically builds the mod whenever a commit is pushed. This verifies that the mod is able to be built with each change.
- Adds .DS_Store files to the .gitignore (because MacOS is dumb).

Dependancy changes: 
- Updates the game version to 1.16.3, the Fabric loader version to 0.10.0+build.208, Fabric API to 0.22.1+build.409-1.16, and Fabric-loom to 0.5-SNAPSHOT.
- Removes the Ladder API dependency, as 1.16 added a tag which serves the same purpose.
- Switches to using FabricBlockSettings v1, as v0 is deprecated.

Buildscript changes:
- Changes the Gradle build script from using sourceCompatibility / targetCompatibility to using languageVersion, to ensure that the mod is built to be Java 8 compatible.
- Uses the Gradle build script to automatically minify .json files in the built mod .jar file, to lower the size of a built .jar file and to verify that all .json files are valid on build.
- Uses the Gradle build script to automatically declare in the fabric.mod.json file that the mod depends on the versions of Minecraft, the Fabric loader, and the Fabric API that the mod was built with, or above.

Other:
- Losslessly shrinks the size of all images, through a combination of exiftool, oxipng, pngwolf-zopfli and advpng. The optimisations to file size do not reduce the quality of the images in any way.

### CODE REVIEW

**Comment by NeRdTheNed** [comment]
@Gaz492

**Comment by NeRdTheNed** [comment]
Sorry, I accidentally pressed the wrong button! I might continue to update this for 1.16.3.

**Comment by Gaz492** [comment]
No worries, if you do update it to 1.16.3 let me know, ill also have a look at merging this in the next day or two

**Comment by NeRdTheNed** [comment]
No problems! It seems to have been pretty easy, as I've done some testing and everything works OK. I'll probably look at merging some features from other branches as well.

**Comment by NeRdTheNed** [comment]
@Gaz492 I think this should be ready to merge! This PR went through a bit of scope creep, so feel free to reject parts of it if you don't feel that the project needs them.

**Pull request merged**
